DEBUG    temporalio.worker._activity:_activity.py:276 Running activity say_hello (token b'\n$8aa290fa-b00f-4fa1-a139-85696fcc157a\x12-workflow-eb4d734f-191f-4c08-b75d-6c566c4dac47\x1a$7ddc72f6-0bd4-4f4b-a49e-add7d34adbac \x05(\x012\x011B\tsay_helloJ\x08\x08\x01\x10\xb7\x9a@\x18\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'say_hello', 'attempt': 1, 'namespace': 'default', 'task_queue': 'ab9d30d1-0907-489e-ac0a-ab8a9527ba4c', 'workflow_id': 'workflow-eb4d734f-191f-4c08-b75d-6c566c4dac47', 'workflow_run_id': '7ddc72f6-0bd4-4f4b-a49e-add7d34adbac', 'workflow_type': 'SayHelloWorkflow'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\n$8aa290fa-b00f-4fa1-a139-85696fcc157a\022-workflow-eb4d734f-191f-4c08-b75d-6c566c4dac47\032$7ddc72f6-0bd4-4f4b-a49e-add7d34adbac \005(\0012\0011B\tsay_helloJ\010\010\001\020\267\232@\030\001"
result {
  completed {
    result {
      metadata {
        key: "encoding"
        value: "json/plain"
      }
      data: "\"Hello, Temporal!\""
    }
  }
}

DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID 7ddc72f6-0bd4-4f4b-a49e-add7d34adbac
Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/testing/_workflow.py", line 493, in execute_workflow
    return await super().execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_interceptor.py", line 328, in execute_workflow
    return await self.next.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_replayer.py", line 52, in run
    raise ApplicationError("Intentional error")
temporalio.exceptions.ApplicationError: Intentional error
INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities
DEBUG    temporalio.worker._workflow_instance:_workflow_instance.py:1788 Workflow raised failure with run ID 7ddc72f6-0bd4-4f4b-a49e-add7d34adbac
Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 1767, in _run_top_level_workflow_function
    await coro
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 831, in run_workflow
    result = await self._inbound.execute_workflow(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_workflow_instance.py", line 2099, in execute_workflow
    return await input.run_fn(*args)
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_replayer.py", line 52, in run
    raise ApplicationError("Intentional error")
temporalio.exceptions.ApplicationError: Intentional error
DEBUG    temporalio.worker._workflow:_workflow.py:299 Evicting workflow with run ID 7ddc72f6-0bd4-4f4b-a49e-add7d34adbac, message: Always evict workflows after replay