DEBUG    temporalio.worker._activity:_activity.py:276 Running activity some_activity (token b'\x00\x07default\x00$2cb64caa-3bbb-4c13-83ba-b545de15c741\x00$bad617d4-15c3-4c28-8e81-f16abddafe72\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:test_activity.py:619 Changing count from 0 to 9 ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
WARNING  temporalio.activity:_activity.py:493 Completing activity as failed ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 453, in _run_activity
    result = await impl.execute_activity(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 711, in execute_activity
    return await input.fn(*input.args)
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py", line 623, in some_activity
    raise RuntimeError("Try again!")
RuntimeError: Try again!
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details (9,) ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 1, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\000\007default\000$2cb64caa-3bbb-4c13-83ba-b545de15c741\000$bad617d4-15c3-4c28-8e81-f16abddafe72\000\000\000\000\000\000\000\005\000\000\000\001"
result {
  failed {
    failure {
      message: "Try again!"
      stack_trace: "  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 453, in _run_activity\n    result = await impl.execute_activity(input)\n\n  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 711, in execute_activity\n    return await input.fn(*input.args)\n\n  File \"/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py\", line 623, in some_activity\n    raise RuntimeError(\"Try again!\")\n"
      application_failure_info {
        type: "RuntimeError"
      }
    }
  }
}

DEBUG    temporalio.worker._activity:_activity.py:276 Running activity some_activity (token b'\x00\x07default\x00$2cb64caa-3bbb-4c13-83ba-b545de15c741\x00$bad617d4-15c3-4c28-8e81-f16abddafe72\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x02')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 2, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:test_activity.py:619 Changing count from 9 to 18 ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 2, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
WARNING  temporalio.activity:_activity.py:493 Completing activity as failed ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 2, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 453, in _run_activity
    result = await impl.execute_activity(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 711, in execute_activity
    return await input.fn(*input.args)
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py", line 623, in some_activity
    raise RuntimeError("Try again!")
RuntimeError: Try again!
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details (18,) ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 2, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\000\007default\000$2cb64caa-3bbb-4c13-83ba-b545de15c741\000$bad617d4-15c3-4c28-8e81-f16abddafe72\000\000\000\000\000\000\000\005\000\000\000\002"
result {
  failed {
    failure {
      message: "Try again!"
      stack_trace: "  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 453, in _run_activity\n    result = await impl.execute_activity(input)\n\n  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 711, in execute_activity\n    return await input.fn(*input.args)\n\n  File \"/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py\", line 623, in some_activity\n    raise RuntimeError(\"Try again!\")\n"
      application_failure_info {
        type: "RuntimeError"
      }
    }
  }
}

DEBUG    temporalio.worker._activity:_activity.py:276 Running activity some_activity (token b'\x00\x07default\x00$2cb64caa-3bbb-4c13-83ba-b545de15c741\x00$bad617d4-15c3-4c28-8e81-f16abddafe72\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x03')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 3, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:test_activity.py:619 Changing count from 18 to 27 ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 3, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
WARNING  temporalio.activity:_activity.py:493 Completing activity as failed ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 3, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
Traceback (most recent call last):
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 453, in _run_activity
    result = await impl.execute_activity(input)
  File "/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py", line 711, in execute_activity
    return await input.fn(*input.args)
  File "/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py", line 623, in some_activity
    raise RuntimeError("Try again!")
RuntimeError: Try again!
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details (27,) ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 3, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\000\007default\000$2cb64caa-3bbb-4c13-83ba-b545de15c741\000$bad617d4-15c3-4c28-8e81-f16abddafe72\000\000\000\000\000\000\000\005\000\000\000\003"
result {
  failed {
    failure {
      message: "Try again!"
      stack_trace: "  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 453, in _run_activity\n    result = await impl.execute_activity(input)\n\n  File \"/home/runner/work/sdk-python/sdk-python/temporalio/worker/_activity.py\", line 711, in execute_activity\n    return await input.fn(*input.args)\n\n  File \"/home/runner/work/sdk-python/sdk-python/tests/worker/test_activity.py\", line 623, in some_activity\n    raise RuntimeError(\"Try again!\")\n"
      application_failure_info {
        type: "RuntimeError"
      }
    }
  }
}

DEBUG    temporalio.worker._activity:_activity.py:276 Running activity some_activity (token b'\x00\x07default\x00$2cb64caa-3bbb-4c13-83ba-b545de15c741\x00$bad617d4-15c3-4c28-8e81-f16abddafe72\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x04')
DEBUG    temporalio.activity:_activity.py:440 Starting activity ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 4, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:test_activity.py:619 Changing count from 27 to 36 ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 4, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.activity:_activity.py:255 Recording heartbeat with details (36,) ({'activity_id': '1', 'activity_type': 'some_activity', 'attempt': 4, 'namespace': 'default', 'task_queue': 'cfc2e87f-f4dd-4322-b265-753b9c63fae6', 'workflow_id': '2cb64caa-3bbb-4c13-83ba-b545de15c741', 'workflow_run_id': 'bad617d4-15c3-4c28-8e81-f16abddafe72', 'workflow_type': 'kitchen_sink'})
DEBUG    temporalio.worker._activity:_activity.py:527 Completing activity with completion: task_token: "\000\007default\000$2cb64caa-3bbb-4c13-83ba-b545de15c741\000$bad617d4-15c3-4c28-8e81-f16abddafe72\000\000\000\000\000\000\000\005\000\000\000\004"
result {
  completed {
    result {
      metadata {
        key: "encoding"
        value: "json/plain"
      }
      data: "\"final count: 36\""
    }
  }
}

INFO     temporalio.worker._worker:_worker.py:523 Beginning worker shutdown, will wait 0:00:00 before cancelling activities